### ISSUE TITLE
On Android 5.0 the application crash the you call showFlashDialog Method

### ISSUE THREAD

**Issue by eric-ampire** [gabriel-TheCode/AestheticDialogs#3]
android.view.InflateException: Binary XML file line #26: Error inflating class androidx.appcompat.widget.AppCompatImageView
        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at com.thecode.aestheticdialogs.AestheticDialog.showFlashDialog(AestheticDialog.java:235)

**Comment by eric-ampire** [comment]
And sometime the app throw this exception

Caused by: java.lang.OutOfMemoryError: Failed to allocate a 29203212 byte allocation with 15504676 free bytes and 14MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:741)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:562)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1014)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:3723)
        at android.content.res.Resources.loadDrawable(Resources.java:3596)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:750)
        at android.widget.ImageView.<init>(ImageView.java:151)
        at android.widget.ImageView.<init>(ImageView.java:140)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at com.thecode.aestheticdialogs.AestheticDialog.showDrake(AestheticDialog.java:323)

**Comment by eric-ampire** [comment]
And I have seen that the problem can be solved by adding this lines in the application section of Manifest file

android:largeHeap="true"

**Comment by gabriel-TheCode** [comment]
Thanks for your feedback; I found the origin of the problem. 
This issue will be resolved in the next release.

**Comment by gabriel-TheCode** [comment]
[1.2.1](https://github.com/gabriel-TheCode/AestheticDialogs/releases/tag/1.2.1)
